module.exports = {
    SERVER:{
        port:5000,
        static_url: "public",
        cors:{
            allowed_host:['*']
        },
        security:{
            jwt_secret_key:"ufvghf_crexythj__bhgctwazes_xdcfvb8-65632a6t6_6hg438:76897098y_87g76f9"
        }
    },
    DATABASE:{
        development:{
            name:"horas",
            user:"horas",
            password:"horas",
            port:"37740",
            host:"ds137740.mlab.com",
            provider:"mlab"
        },
        producction:{
            name:"",
            user:"",
            password:"",
            port:"",
            host:"",
            provider:"mlab"
        }
    }
};